### ISSUE TITLE
ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by magicode** [JeanSebTr/node-python#2]
js code

``` javascript
 var cv = python.import('cv2');

```

error

```

ImportError: numpy.core.multiarray failed to import
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/apport_python_hook.py", line 64, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python2.7/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python2.7/dist-packages/apport/report.py", line 16, in <module>
    from xml.parsers.expat import ExpatError
  File "/usr/lib/python2.7/xml/parsers/expat.py", line 4, in <module>
    from pyexpat import *
ImportError: /usr/lib/python2.7/lib-dynload/pyexpat.x86_64-linux-gnu.so: undefined symbol: _Py_ZeroStruct

Original exception was:
ImportError: numpy.core.multiarray failed to import

/*/test2.js:6
var cv = python.import('cv2');
                      ^
Error: numpy.core.multiarray failed to import
    at Object.<anonymous> (/*/test2.js:6:23)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:901:3


```

**Comment by JeanSebTr** [comment]
Hi,

this seems more like a linker error than an error with node-python, are you sure this code run fine in plain python ?

**Comment by magicode** [comment]
I do not know python 

i try this code and it works well

``` python
 import cv2 
```

**Comment by JeanSebTr** [comment]
Can you tell me more about your setup?
- Which linux distribution do you use (+version)?
- What's your version of Nodejs and npm ?

**Comment by magicode** [comment]
Ubuntu  13.04, Raring Ringtail

node v0.10.10

npm 1.2.25

**Comment by magicode** [comment]
this log of compile

```
> node-python@0.0.3 install node_modules/node-python
> node-gyp rebuild

make: Entering directory `node_modules/node-python/build'
  CXX(target) Release/obj.target/binding/src/binding.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
  CXX(target) Release/obj.target/binding/src/utils.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
  CXX(target) Release/obj.target/binding/src/py_object_wrapper.o
cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++ [enabled by default]
../src/py_object_wrapper.cc: In static member function ‘static v8::Handle<v8::Value> PyObjectWrapper::ValueOf(const v8::Arguments&)’:
../src/py_object_wrapper.cc:156:26: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
../src/py_object_wrapper.cc:157:28: warning: deprecated conversion from string constant to ‘char*’ [-Wwrite-strings]
../src/py_object_wrapper.cc:162:19: warning: unused variable ‘cstr’ [-Wunused-variable]
  SOLINK_MODULE(target) Release/obj.target/binding.node
  SOLINK_MODULE(target) Release/obj.target/binding.node: Finished
  COPY Release/binding.node
make: Leaving directory `node_modules/node-python/build'

```
